services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: spotifydb
      MYSQL_USER: spotify
      MYSQL_PASSWORD: spotifypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spotify_analyzer:
    build:
      context: .
      dockerfile: src/SpotifyAnalyzer/Dockerfile
    container_name: spotify-analyzer
    image: spotify-analyzer:latest
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/uploads
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: spotify
      DB_PASSWORD: spotifypass
      DB_NAME: spotifydb
    working_dir: /app
    depends_on:
      - mysql
    restart: unless-stopped

  spotify_interface:
    build:
      context: .
      dockerfile: src/SpotifyInterface/Dockerfile
    container_name: spotify-interface
    image: spotify-interface:latest
    volumes:
      - uploads:/app/uploads
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: spotify
      DB_PASSWORD: spotifypass
      DB_NAME: spotifydb
    working_dir: /app
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
  uploads:
