DEBUG: bool = True
PORT: int = 5000
HOST: str = "0.0.0.0"
# STATIC_PATH: str = "../static"
STATIC_PATH: str = "/app/src/static"
# TEMPLATES_PATH: str = "../templates"
TEMPLATES_PATH: str = "/app/src/templates"
# SQL_PATH: str = "./src/sql"
SQL_PATH: str = "/app/src/sql"
FLASK_SECRET_KEY: str = "mikudayo"
DATABASE_PATH: str = "/app/database/database.db"
